### PR TITLE
Quantization support

### PR DESCRIPTION
**Pull request by kkoz**

### CODE REVIEW

**Comment by chris-allan** [comment]
Looks good. Do you think we can do it on 0.5.x and then merge back into master?

**Comment by kkoz** [comment]
Opened #70 which makes these changes on 0.5.x

**Comment by chris-allan** [comment]
Now that #77 has been merged, needs to have `master` merged in and probably needs some refactoring before this can be merged.

**Comment by chris-allan** [comment]
Closing as this has already been included in a different form with #77.

**Pull request closed without merging**
