### PR TITLE
Re-include xalan as a dependency of the image-region micro-service

### PR DESCRIPTION
**Pull request by sbesson**
This library is required for upgrading older version of the OME-XML schema (currently at 2016-06) using the XSLT transformation sheets in the memo regeneration utility.
Without it, the XML transformation will fail and the reader stack will typically fallback to the generic TIFF reader causing metadata mismatch when reading planes/series greater than zero.

This can be tested by importing a multidimensional multi-file OME-TIFF created with an old version of the OME data model e.g. https://downloads.openmicroscopy.org/images/OME-TIFF/2013-06/tubhiswt-4D/ and regenerating the memo file using the utility shipped with the micro-service. With the current version of the micro-service, the memo file will be generated using the standard TIFF reader and any rendering call on a plane other than the first one should result in an `Error instantiating pixel buffer` due to an underlying `java.lang.IllegalArgumentException`.
With this PR included, the rendering calls should work as expected for all planes

### CODE REVIEW

**Review by melissalinkert — APPROVED** [review]
:+1: We might want to evaluate other places where this dependency is excluded too (e.g. https://github.com/search?q=org%3Aglencoesoftware+%22exclude+group%3A+%27xalan%27%22&type=code)

As discussed separately with @sbesson, a potential follow-up is to warn in the memo regenerator if the regenerated memo's reader does not match the DB reader (and/or the previous memo's reader), as that could have helped to catch this issue sooner.

**Review by chris-allan — CHANGES_REQUESTED** [review]
Throw a quick unit test in to make sure that the requisite classes are on the classpath?

**Comment by chris-allan** [comment]
Do we need to initialize everything and run what is essentially an integration test to check if Xalan is on the classpath?

**Comment by sbesson** [comment]
[576cfdc](https://github.com/glencoesoftware/omero-ms-image-region/pull/147/commits/576cfdcc790fc18aeaf06b2e657b69fa6c50edb8) should include a first unit test for the `MemoRegenerator` class which uses the [tubishwt-2D](https://downloads.openmicroscopy.org/images/OME-TIFF/2013-06/tubhiswt-2D/) as a representative example.

Running the tests  on top of the current HEAD of the micro-service should fail with an `java.lang.AssertionError: expected:<2> but was:<1>` due to the missing `xalan` library. 
With the library re-included the test should pass and help to catch future regressions

**Comment by sbesson** [comment]
> Do we need to initialize everything and run what is essentially an integration test to check if Xalan is on the classpath?

Definitely not necessary. Last commit should keep the tests minimal for now and throw a `ClassNotFoundException` is `xalan` is not on the runtime classpath.

**Comment by chris-allan** [comment]
> > Do we need to initialize everything and run what is essentially an integration test to check if Xalan is on the classpath?
> 
> Definitely not necessary. Last commit should keep the tests minimal for now and throw a `ClassNotFoundException` is `xalan` is not on the runtime classpath.

:+1: Let's loose the TIFFs from 576cfdcc790fc18aeaf06b2e657b69fa6c50edb8 then? Maybe just force push it away?

**Pull request merged**
