### PR TITLE
Thorough Zarr pixel buffer implementation

### PR DESCRIPTION
**Pull request by chris-allan**
Thorough Zarr pixel buffer implementation this is ready for use inside the server.

### CODE REVIEW

**Comment by melissalinkert** [comment]
I don't see anything obviously worrying after reading through this, but haven't directly tested.

**Comment by kkoz** [comment]
Looks good to me. I did notice when testing that if you request a non-existent resolution level, you get
```2021-12-13 07:51:45,164 [render-image-region-pool-0] ERROR c.g.o.m.i.r.ImageRegionRequestHandler - Exception while retrieving image region
java.lang.RuntimeException: java.io.IOException: '.zarray' expected but is not readable or missing in store.
	at com.glencoesoftware.omero.ms.image.region.ZarrPixelBuffer.setResolutionLevel(ZarrPixelBuffer.java:713)
```
And the client gets a 404. Is this acceptable or do we want a more informative error message?

**Review by kkoz — APPROVED** [review]

**Comment by chris-allan** [comment]
@kkoz: Let me know if a780a4d3b8c89e343fdc6f54d9b0361ec69cd93b was in line with your thinking.

**Comment by kkoz** [comment]
Looks good to me.

**Pull request merged**
