### PR TITLE
Added feature where OPTIONS requests will inform the client that the …

### PR DESCRIPTION
**Pull request by kkoz**
…requests is being handled by a microservice.

### CODE REVIEW

**Comment by chris-allan** [comment]
When in development mode in an IDE or similar:

```
{
  "is_microservice" : "true",
  "microservice_name" : "ImageRegionMicroservice",
  "version" : "development"
}
```

When using a build where the JAR gets the proper manifest:

```
{
  "is_microservice" : "true",
  "microservice_name" : "ImageRegionMicroservice",
  "version" : "0.4.0-SNAPSHOT"
}
```

/cc @knabar

**Comment by chris-allan** [comment]
Might be a good idea for "is_microservice" to be a boolean. Thoughts @knabar?

**Comment by knabar** [comment]
Optimally a boolean would be better, although the `is_microservice` setting is not really relevant - applications like PathViewer would be more concerned about available functionality, not how it is delivered.

How about something like this?
```
{
  "provider": "ImageRegionMicroservice",
  "version": "0.4.0-SNAPSHOT",
  "services": ["flipRegion", "flipMask"]
}
```

In PathViewer, all I'm interested in is running e.g. `data.services.indexOf("flipMask") > -1`.

**Comment by chris-allan** [comment]
Sounds reasonable to me. Maybe a `features` array instead?

**Comment by knabar** [comment]
`features` sounds good, and it only needs to include what's not available in regular omero:

```
{
  "provider": "ImageRegionMicroservice",
  "version": "0.4.0-SNAPSHOT",
  "features": ["flip", "mask-color"]
}
```

**Comment by knabar** [comment]
Somewhat final `features` list:

`["flip", "mask-color", "png-tiles"]`

**Pull request merged**
